import express from 'express';
import * as ExpressSession from 'express-session';

import bodyParser from "body-parser";
import expressValidator from "express-validator";

import passport from "passport";
import * as passportConfig from "./security/passport";

import path from "path";

import { LoginController } from './Controllers/LoginController';

const expressApp: express.Application = express();
expressApp.set('view engine', 'ejs');
expressApp.set('views', path.join(__dirname, './../../src/client/views')) // . dir is the typescript_dist dir
expressApp.use(express.static(path.join('client_public'))); // client_public is generated by copy grunt task

expressApp.use("/", LoginController);



//expressApp.use(compression());
//expressApp.use(bodyParser.json());
//expressApp.use(bodyParser.urlencoded({ extended: true }));
//expressApp.use(expressValidator());

//expressApp.use(session({
//  resave: true,
//  saveUninitialized: true,
//  secret: SESSION_SECRET,
//}));



//expressApp.use(ExpressSession({
//    secret: 'i-love-husky',
//    resave: false,
//    saveUninitialized: true
//}));


//app.use(passport.initialize());
//app.use(passport.session());
//app.use(flash());
//app.use(lusca.xframe("SAMEORIGIN"));

export const ExpressWebApp: express.Application = expressApp;

